name: Docker Image CI

# 触发条件
on:
  workflow_dispatch:
        
env:
  REGISTRY: ghcr.io
  IMAGE: d9lab/Ant-Media-Server
  ANT_VER: 2.5.3
  
jobs:
  build:
    name: Push Docker image
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v3
    - name: Prepare files
      run: |
        wget https://github.com/ant-media/Ant-Media-Server/releases/latest/download/ant-media-server-community-${{ env.ANT_VER }}.zip -nv -O ant.zip
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    # 登录 ghcr.io
    - name: Login ghcr.io
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    # 镜像元数据操作
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4
      with:
        labels: |
          MAINTAINER=Disappear9
          org.opencontainers.image.title=Ant-Media-Server
          org.opencontainers.image.description=Ant-Media-Server
          org.opencontainers.image.url=https://github.com/D9Lab/Ant-Media-Server-Docker
          org.opencontainers.image.source=https://github.com/ant-media/Ant-Media-Server
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=v${{ env.ANT_VER }},enable={{is_default_branch}}
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE }}
    
    # 构建 并 推送镜像
    - name: build and push docker image
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: .
        network: host
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}
